# Generated by Django 3.1.4 on 2020-12-11 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_institution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthinstitution',
            name='province',
        ),
    ]
