# Generated by Django 3.1.4 on 2020-12-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={'verbose_name_plural': 'medical histories'},
        ),
    ]
