# Generated by Django 3.1.4 on 2020-12-09 06:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myauth', '0002_account_is_active'),
        ('health_institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myauth.account')),
                ('birthday', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='The format should be dd/mm/yyyy', regex='^([1-9]|0[1-9]|[12]\\d|3[0-1])\\/([1-9]|0[1-9]|1[012])\\/[1-9]\\d+$')])),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\+[1-9]\\d{1,2}\\d{11,12}$')])),
                ('health_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_institution.healthinstitution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
