# Generated by Django 3.1.4 on 2020-12-09 07:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('do_activity', models.BooleanField()),
                ('do_smoke', models.BooleanField()),
                ('take_medicine', models.BooleanField()),
                ('have_family_illness', models.BooleanField()),
                ('sistole', models.FloatField()),
                ('diastole', models.FloatField()),
                ('blood_sugar_level', models.FloatField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('waist_size', models.FloatField()),
                ('cholesterol_level', models.FloatField()),
                ('blood_volume', models.FloatField()),
                ('oxygen_saturation', models.FloatField()),
                ('oxygen_volume', models.FloatField()),
                ('lung_sounds', models.FileField(upload_to='')),
                ('cardiovascular_risk', models.FloatField()),
                ('diabetes_risk', models.FloatField()),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
