# Generated by Django 3.1.4 on 2020-12-08 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('do_activity', models.BooleanField()),
                ('do_smoke', models.BooleanField()),
                ('take_medicine', models.BooleanField()),
                ('have_family_illness', models.BooleanField()),
                ('sistole', models.FloatField()),
                ('diastole', models.FloatField()),
                ('blood_sugar_level', models.FloatField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('waist_size', models.FloatField()),
                ('cholesterol_level', models.FloatField()),
                ('blood_volume', models.FloatField()),
                ('oxygen_saturation', models.FloatField()),
                ('oxygen_volume', models.FloatField()),
                ('lung_sounds', models.FileField(upload_to='')),
                ('cardiovascular_risk', models.FloatField()),
                ('diabetes_risk', models.FloatField()),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('common.basemodel',),
        ),
    ]
