# Generated by Django 3.0.8 on 2020-12-12 01:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='blood_volume',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='cholesterol_level',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='lung_sounds',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='oxygen_volume',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='cholesterol_total',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='blood_sugar_level',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='cardiovascular_risk',
            field=models.FloatField(default=0, verbose_name=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='diabetes_risk',
            field=models.FloatField(default=0, verbose_name=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='diastole',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='do_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='do_smoke',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='have_family_illness',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='height',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='oxygen_saturation',
            field=models.FloatField(default=0, verbose_name=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='sistole',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='take_medicine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='waist_size',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='weight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
