# Generated by Django 3.1.4 on 2020-12-12 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_record', '0002_auto_20201212_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthrecord',
            old_name='have_family_illness',
            new_name='have_medical_history',
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='cardiovascular_risk',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='diabetes_risk',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='oxygen_saturation',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
