# Generated by Django 3.1.4 on 2020-12-12 23:12

from django.db import migrations

def drop_all_records_without_owner(apps, schema_editor):
    HealthRecord = apps.get_model('health_record', 'HealthRecord')
    HealthRecord.objects.filter(patient = None).delete()

def do_nothing(*args, **kwargs):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('health_record', '0003_auto_20201212_0842'),
    ]

    operations = [
        migrations.RunPython(
            drop_all_records_without_owner,
            do_nothing,
        )
    ]
