# Generated by Django 3.1.4 on 2020-12-12 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20201212_1257'),
        ('health_record', '0004_auto_20201213_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
