# Generated by Django 3.1.4 on 2020-12-07 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_institution', '0001_initial'),
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myauth.user')),
                ('nik', models.CharField(max_length=16)),
                ('physical_activity_type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Extremely Inactive'), (2, 'Sedentary'), (3, 'Moderately Active'), (4, 'Vigorously Active'), (5, 'Extremely Active')], default=0)),
                ('smoke_amount', models.PositiveIntegerField()),
                ('is_male', models.BooleanField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('health_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_institution.healthinstitution')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('myauth.user',),
        ),
    ]
