# Generated by Django 3.1.4 on 2020-12-25 12:54

from django.db import migrations

def activate_all_patients(apps, schema_editor):
    Patient = apps.get_model('patient', 'Patient')
    for patient in Patient.objects.all():
        patient.account.is_active = True
        patient.account.save()

def deactivate_all_patients(apps, schema_editor):
    Patient = apps.get_model('patient', 'Patient')
    for patient in Patient.objects.all():
        patient.account.is_active = False
        patient.account.save()

class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20201212_1257'),
    ]

    operations = [
        migrations.RunPython(
            activate_all_patients,
            deactivate_all_patients,
        )
    ]
