# Generated by Django 3.1.4 on 2021-10-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20201225_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nik',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
