# Generated by Django 3.1.4 on 2020-12-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_account_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Admin'), (2, 'Operator'), (3, 'Patient')], default=0),
        ),
    ]
