# Generated by Django 3.1.4 on 2021-10-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_auto_20201209_1408'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='account',
            name='role',
        ),
    ]
