# Generated by Django 3.1.4 on 2020-12-13 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lung_sound_classification', '0002_auto_20201213_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lungsoundclassification',
            name='reserved_id',
        ),
    ]
