# Generated by Django 3.1.4 on 2020-12-13 01:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

from apps.v1.lung_sound_classification.constants import RESERVED_IDS

def supply_reserved_id(apps, schema_editor):
    ReservedID = apps.get_model('lung_sound_classification', 'ReservedID')
    for id in RESERVED_IDS:
        ReservedID.objects.create(id = id)

def drop_reserved_id(apps, schema_editor):
    ReservedID = apps.get_model('lung_sound_classification', 'ReservedID')
    ReservedID.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lung_sound_classification', '0003_remove_lungsoundclassification_reserved_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedID',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
        migrations.AddField(
            model_name='lungsoundclassification',
            name='reserved_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lung_sound_classification', to='lung_sound_classification.reservedid'),
        ),
        migrations.RunPython(
            supply_reserved_id,
            drop_reserved_id,
        )
    ]
