# Generated by Django 3.1.4 on 2020-12-13 01:21

from django.db import migrations, models
import django.db.models.deletion

def set_reserved_id_on_classification(apps, schema_editor):
    LungSoundClassification = apps.get_model('lung_sound_classification', 'LungSoundClassification')
    ReservedID = apps.get_model('lung_sound_classification', 'ReservedID')
    for instance in LungSoundClassification.objects.filter(health_record = None):
        instance.reserved_id = ReservedID.objects.filter(lung_sound_classification = None)[0]
        instance.save()

def do_nothing(*args, **kwargs):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('health_record', '0005_auto_20201213_0619'),
        ('lung_sound_classification', '0004_auto_20201213_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='lungsoundclassification',
            name='health_record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health_record.healthrecord'),
        ),
        migrations.RunPython(
            set_reserved_id_on_classification,
            do_nothing,
        )
    ]
