# Generated by Django 3.1.4 on 2020-12-25 14:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_record', '0005_auto_20201213_0619'),
        ('lung_sound_classification', '0005_lungsoundclassification_health_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lungsoundclassification',
            name='health_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lung_sound_classification', to='health_record.healthrecord'),
        ),
        migrations.AlterField(
            model_name='lungsoundclassification',
            name='result',
            field=models.PositiveSmallIntegerField(choices=[(99, 'Unclassified'), (1, 'Crackles'), (2, 'Wheezing'), (3, 'Wheezing and Crackles')]),
        ),
        migrations.AlterField(
            model_name='reservedid',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9998)]),
        ),
    ]
