# Generated by Django 3.0.8 on 2021-01-27 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lung_sound_classification', '0006_auto_20201225_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lungsoundclassification',
            name='likelihood_percentage',
        ),
        migrations.AddField(
            model_name='lungsoundclassification',
            name='min_support',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
